{
  "report_id": "IR-20240208-001",
  "title": "Checkout URL Error",
  "error_name": "AxiosError: Network Error",
  "severity": "SEV-1",
  "status": "Open",
  "description": "User reported unable to checkout",
  "stack_trace": [
    "ERROR:root:Error Message: AxiosError    ",
    "ERROR:root:Stack Trace: AxiosError: Network Error",
    "at XMLHttpRequest.handleError (webpack-internal:///(app-client)/./node_modules/axios/lib/adapters/xhr.js:172:14)",
    "ERROR:root:Additional Info: http://localhost:3000/api/4a41a355-030c-4c8d-ad8a-1d0b57c491b8/checskout"
  ],
  "solution": "",
  "affected_services": [],
  "timestamp": "2024-02-08T16:03:00Z",
  "updates": [
  ],
  "tags": [],
  "incident_duration": "",
  "impact": ""
}
